### ISSUE TITLE
TypeError for first time users

### ISSUE THREAD

**Issue by jrasm91** [kshetline/aw-clock#24]
I seem to be getting a type error here: https://github.com/kshetline/aw-clock/blob/master/src/settings.ts#L41

I believe it is caused by this line: https://github.com/kshetline/aw-clock/blob/master/src/settings.ts#L82

`Cookies.get('ampm')` isn't set, so it returns `undefined`, which then leads to `s` being `undefined` in the expression `s = s.toLowerCase();` 

I was able to reproduce it in an incognito window every time. Once the `ampm` cookie is set, it seems to work fine.

![image](https://user-images.githubusercontent.com/4334196/92550594-b1867900-f210-11ea-9df7-12a19a92b9e6.png)

**Comment by kshetline** [comment]
Good catch. Thanks!
