### ISSUE TITLE
Feature request - add wind forecast(s)

### ISSUE THREAD

**Issue by emxsys** [kshetline/aw-clock#30]
The daily and hourly weather in my region (Ventura, Californai) is dominated by the prevailing winds, much more so than precipitation (unless it's raining, then we go wacky with news coverage of puddles on the roads). When _Santa Ana_ winds arrive, significant changes in wind speeds and direction can change by the hour. The **aw-clock** would have more value if wind forecasts were added. Wind forecasts help with the following (just to name a few):

- Wildfire behavior predictions
- Beach recreation
- Aviation

**Comment by kshetline** [comment]
I've considered this before, but I've been hesitant simply because I can't think of a good place to squeeze that additional information into the screen layout. Do you have some suggestions?

**Comment by emxsys** [comment]
For the hourly winds, I was thinking that you could interpret the forecast data and convert to wind barbs for display.. E.g., 
![image](https://user-images.githubusercontent.com/191515/95683135-382acf00-0b9e-11eb-872a-15ec9f467558.png)

I have a collection of .svg files here: https://github.com/WorldWindEarth/explorer/tree/develop/root/js/model/images/weather

**Comment by emxsys** [comment]
I concur with all your ideas and observations. Especially regarding wind gusts; they are difficult to deal with graphically.

**Comment by datagod** [comment]
I'm sorry to interject into this thread but I love this project but I am
out of my league when it comes to figuring out how to apply an upgrade. can
somebody please point me in the direction?

**Comment by kshetline** [comment]
I've added wind speed information. Please let me know what you think.

**Comment by emxsys** [comment]
Superb!  Excellent work. Your implementation really exceeded my hopes. We're having a "wind event" today, so I'm truly able to evaluate and appreciate it.

Your wind gust display is intuitive and concise. Is that an original idea? I have not seen it displayed like that before. Very Nice!

**Comment by kshetline** [comment]
If you're talking about the way I show the wind gust speed as an arc along the clock face, I'm pretty sure that's my idea (I haven't seen it elsewhere yet). Overlaying normal wind barbs on top of gust wind barbs, so the extra barbs poke out from behind in red, is something I thought up on my own, but then I found I definitely didn't think of that one first.

I'm happy to hear you like how it turned out.
