### ISSUE TITLE
Feature request - indicate day and night in the planet display

### ISSUE THREAD

**Issue by emxsys** [kshetline/aw-clock#33]
_My wife and I enjoy using the astronomy dial to locate the planets on most evenings. We find the planet display very enlightening._

For your consideration, shade the planet display to indicate both the daytime and nighttime sky.  

- Rationale: to quickly identify which planets are visible within the night sky. 
- Suggestion: shade the planet display's dial segment that is coincident with Sun's _above the horzon_ arc with a lighter color.

_Thanks for a great clock!_

**Comment by emxsys** [comment]
I'm not sure that this is a great idea. It seems it only makes sense that the daylight shading is applied when the Sun is above the horizon, and in that case, the Sun's "above the horizon arc" is adequate.

I'm retracting this feature request.

**Comment by kshetline** [comment]
I found a way to handle this idea, which is now in the latest version. The arcs that show when a planet is above the local horizon are now purple along the sections of the arcs when the sun is below the horizon.

**Comment by emxsys** [comment]
Great! That was unexpected. Thanks!

BTW: It was neat to see the alignment of the Moon and Mars, Jupiter and Saturn, and Venus and Mercury just the other day. This is really a _cool clock!_
