### ISSUE TITLE
Feature request - add today's and tomorrow's textual forecasts to the marquee

### ISSUE THREAD

**Issue by emxsys** [kshetline/aw-clock#34]
_In our household we display the weather/clock on our television, which is not a touchscreen.  We use a keyboard/mouse, but it is not convenient._

Please consider adding the _Today_ and _Tomorrow_ forecasts to the marquee.  The additional detail in textual forecasts is richer and more useful than the one-line summary currently displayed in the marquee region.

_If this request is outside the scope of your project, then I would happily pursue it in my fork.  I've already enlarged the marquee region and font, so I'm familiar with that part. But I have not investigated from where to pull the forecasts. Any tips would be appreciated._

**Comment by kshetline** [comment]
Sorry I didn't get back to this sooner, but it's a decent idea. What I most want there myself is the brief summary of the upcoming week that's provided by the Dark Sky forecast. Unfortunately, that API is going away, and hasn't allowed new sign-ups for months, so you're suggestion could be a good substitute. The trick is how to best format it.

**Comment by kshetline** [comment]
I've added your request to the latest release.
