### ISSUE TITLE
Error at Step 8 of install

### ISSUE THREAD

**Issue by sandbox12345** [kshetline/aw-clock#36]
Thank you very much for this program - I'm trying to install on a Raspberry Pi 4 and when I reach Step 8 of the install, an error occurs and installation stops.  I tried rebooting and running the install sequence again, but the same error.  See below.  Thanks for any help.

- Dedicated device setup -
Step 1 of 16: Stopping weatherService if currently running ✔
Step 2 of 16: pigpio already installed ✔
Step 3 of 16: chromium-browser already installed ✔
Step 4 of 16: unclutter already installed ✔
Step 5 of 16: forever already installed ✔
Step 6 of 16: Fonts already installed ✔
Step 7 of 16: xscreensaver already installed ✔
Step 8 of 16: Disabling screen saver ✘
sed: can't read /home/pi/.xscreensaver: No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aw-clock@2.8.0 build: `ts-node build.ts "--bash" "-i"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aw-clock@2.8.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-26T18_44_31_904Z-debug.log

**Comment by kshetline** [comment]
I haven't seen an error like this before, so it's a bit hard for me to guess what's going on. The only thing I can think of trying offhand is to manually uninstall xscreensaver (should be: `sudo apt-get remove xscreensaver`), reboot, and try again.

**Comment by kshetline** [comment]
Since I haven't gotten anymore feedback on this issue, and no similar reports, I'll close it.
