### ISSUE TITLE
Great Project!

### ISSUE THREAD

**Issue by chrisparker787** [kshetline/aw-clock#53]
What a great project - thanks very much!

Small thing - any chance of an option to display the windspeeds in knots instead of kph when in metric?

**Comment by kshetline** [comment]
Check the latest update. I can't do much about textual weather statements, such as those you see when you tap on a day, but the current wind speed can now optionally be displayed in knots while everything else is metric. Also, if you choose knots, wind barbs are based on increments of 5 knots, rather than increments of 2.5 m/s.

**Comment by chrisparker787** [comment]
Brilliant! Thanks Kerry.

Is there a particular update command or should I simply run the installation script again?

**Comment by kshetline** [comment]
You can run the installation script again, but you should see an "Update available" indicator in the upper right corner of the display, and run the update from the Settings dialog (at least if you allowed admin capabilities from the Settings dialog).

**Comment by kshetline** [comment]
Sorry I didn't get back to you sooner. As long as you haven't been modifying the code yourself, just doing a `git pull` from within the aw-clock directory will update the code, then `sudo ./build.sh -i` or `sudo ./build.sh --ddev --reboot` will take care of the rest.

**Comment by chrisparker787** [comment]
Thanks Kerry.

I haven't modified any code, but I got:
`Updating 424ac0e..ae4b4ac
error: Your local changes to the following files would be overwritten by merge:
	package-lock.json
	server/package-lock.json
Please commit your changes or stash them before you merge.`
So I:
`~/aw-clock $ git reset --hard`
then:
`~/aw-clock $ sudo git pull`
then:
`~/aw-clock $ sudo ./build.sh -I`
which results in the error:
`Step 14 of 17: Copying server to top-level dist directory ✘
chown: cannot access 'dist': No such file or directory`

I rebooted and tried again but get the same error.
I then created 'list' directories in root and aw-clock but the same error occurred.

So I completely erased the aw-clock directory and started from scratch.

Success!

Thanks again for a great project!
