### ISSUE TITLE
Beautiful application 

### ISSUE THREAD

**Issue by jitendersaini** [kshetline/aw-clock#99]
This is really a great application and work that is done by you is excellent. I managed to setup it on my rpi3 and I have one observation and one suggestion. It will be great of one detailed diagram of clock gadgets will be provided as there is one widget around the clock face something like small arrow shape that shifts little up and down across a day. I'm still failed to find the purpose of that one 😊. Second this will really be awesome to have Air quality index data also on this clock.

Thanks jitender

**Comment by kshetline** [comment]
What you're seeing is an indicator for wind speed, wind gust speed, and wind direction. It's described in more detail in the documentation.

I'll definitely consider displaying air quality, but I'll have to find a free API that supplies that data, and I haven't found one yet.

**Comment by jitendersaini** [comment]
Hello, 

Thanks for the reply on my question but I think I didn't rightly asked the question 😊 actually I was not asking about wind indicators but asking one blue arch that lies around periphery of the clock face. I'm here with attaching the image to justify my question.![Screenshot_20230714_210459_Chrome~2.jpg](https://github.com/kshetline/aw-clock/assets/4215117/82ae2a51-bd3e-45bc-97a0-17281d6fcf8b)

One more question from my side. In case of rpi kiosk mode if i make some cosmetic changes in src/styles.css then it requires a full build to reflect those changes. Is this possible if changing anything in styles.css pickup the new changes without building it again?

Thanks
Jitender

**Comment by kshetline** [comment]
Yes, that thing you circled is a wind speed indicator. It shows that a light wind, no gusts, is coming from the southeast. For exact wind speed, that can be read in numeric form, but this arc gets wider and changes color as the wind gets stronger, and can show an additional arc for wind gust speed.

**Comment by kshetline** [comment]
As for the styling, you should edit the styles.scss file, then use `npm run build:sass` to update the styles.css file.

**Comment by kshetline** [comment]
Update to what I wrote earlier: You'd still need parts of the build process (you'd have to work this out yourself) to convert the style info into the form that's in the deployment folder (`/home/pi/weather/public` when using defaults). You can run the UI from the development directory too, without fully deploying it, for a faster tweak-and-inspect cycle of trying out various CSS changes before doing a full build again, while not running the browser in kiosk mode.

**Comment by jitendersaini** [comment]
Thanks for your prompt and detailed answer. Yes i tried what earlier you suggested just changing the styles.scss and tried run npm build:sacc but i can see that is taking again good amount of time to build i can see if i build this on Ubuntu and started server then on browser change reflects real time on change of styles.css but in case of ununtu browser is not displaying even default weather info. But so far I'm managing my changes by changing directly styles.css and rebuilding the whole on rpi. I have one more query. While connecting the wired humidity sensor sometimes indoor temperature and humidity readings disappear for few seconds or a minute and come back after that. It is app feature or my sensor issue I don't know. Please refer my images below Thanks ![20230715_112034.jpg](https://github.com/kshetline/aw-clock/assets/4215117/8cfbd585-eda1-4fa5-8d00-c10d2dd00db0)

![20230715_112552.jpg](https://github.com/kshetline/aw-clock/assets/4215117/44cdd8e9-d5e8-4271-ab6f-1d7704f345f6)

![20230715_135451.jpg](https://github.com/kshetline/aw-clock/assets/4215117/997249ac-4897-4a58-81ec-77704a4ebfd1)

**Comment by kshetline** [comment]
I would suspect that it's a problem with the sensor or the wiring to the sensor.

**Comment by jitendersaini** [comment]
Today I've upgraded my RPI with the latest updates and what I can see after update weather forecast text marquee behaviour goes on a toss. Text is displayed but it stops scrolling horizontally.
